/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mp1;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import static mp1.ForgetPassword.strFP;
import static mp1.Login.strU;
import static mp1.Movies.Mname;
import static mp1.Movies.Maddress;
import static mp1.BookTicket.FinalDate;
import static mp1.BookTicket.FinalTime;
import static mp1.BookTicket.FormatD;
import static mp1.BookTicket.LanguageEH;
import static mp1.Seats.seatmatrix;
import static mp1.Seats.BookedSeats;
import static mp1.Seats.count;
import static mp1.Seats.counti;

/**
 *
 * @author prmehta24
 */
public class Confirmation extends javax.swing.JFrame {

    /**
     * Creates new form Confirmation
     * @param user
     */
    String md5(String str){
        String name= str;
        try{
            MessageDigest md = MessageDigest.getInstance("MD5");
            md.update(name.getBytes(),0,name.length());
             name= new BigInteger(1,md.digest()).toString(16);
        }catch(NoSuchAlgorithmException e){
            e.printStackTrace();
        }
        return name;
}
    public void SendEmail(String user){
        int BookId;
        String User= user;
        Random ran = new Random();
        BookId=ran.nextInt(1000000000);
        String str=Integer.toString(BookId);
        str=md5(str);
        ForgetPassword f=new ForgetPassword();
        Scanner sc = new Scanner(System.in);
		final String username = "vectorparker0047@gmail.com"; // enter your mail id
                System.out.print("Enter Admin Password : ");
                String pwd=sc.nextLine();
		final String password = pwd;// enter ur password

		Properties props = new Properties();
		props.put("mail.smtp.auth", "true");
		props.put("mail.smtp.starttls.enable", "true");
		props.put("mail.smtp.host", "smtp.gmail.com");
		props.put("mail.smtp.port", "587");
                props.put("mail.smtp.ssl.trust", "smtp.gmail.com");
                props.put("mail.smtp.ssl.trust", "*");



		Session session = Session.getInstance(props,
		  new javax.mail.Authenticator() {
                        @Override
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(username, password);
			}
		  });

		try {

			Message message = new MimeMessage(session);
			message.setFrom(new InternetAddress("vectorparker0047@gmail.com")); // same email id
			message.setRecipients(Message.RecipientType.TO,
				InternetAddress.parse(User));// whome u have to send mails that person id
			message.setSubject("KITICKET: Your Ticket is Here");
			message.setText("Movie: "+Mname+"\nBooked Seats: "+BookedSeats+"\nLanguage: "+LanguageEH+"\nFormat: "+FormatD+"\nDate: "+FinalDate+"\nTime: "+FinalTime+"\nBooking Id: "+str+"\n\nThank you for choosing us :-)\n\nRegards,\nKITICKET Team");
                        System.out.println("Booking Id : "+str);
                        
			Transport.send(message);

			//String res= JOptionPane.showInputDialog(f,"Email has been sent.\nEnter OTP....");
                        //int i=Integer.parseInt(res);

		} catch (MessagingException e) {
			throw new RuntimeException(e);
		}
        
    }
    public Confirmation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Mov = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ForMAT = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Langu = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Loc = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sEAT = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        DnT = new javax.swing.JLabel();
        Conf = new javax.swing.JButton();
        BackToBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(Maddress)));

        jLabel2.setText("Movie :");

        Mov.setText(Mname);

        jLabel4.setText("Format :");

        ForMAT.setText(FormatD);

        jLabel7.setText("Language :");

        Langu.setText(LanguageEH);

        jLabel9.setText("Location :");

        Loc.setText("KITICKET");

        jLabel11.setText("Seats :");

        sEAT.setText(BookedSeats);

        jLabel13.setText("Date/Time :");

        DnT.setText(FinalDate+", "+FinalTime);

        Conf.setBackground(new java.awt.Color(0, 255, 0));
        Conf.setText("Confirm");
        Conf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfActionPerformed(evt);
            }
        });
        Conf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ConfKeyPressed(evt);
            }
        });

        BackToBT.setBackground(new java.awt.Color(255, 0, 0));
        BackToBT.setText("Back");
        BackToBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToBTActionPerformed(evt);
            }
        });
        BackToBT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BackToBTKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(ForMAT))
                            .addComponent(Mov)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Langu))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sEAT)
                            .addComponent(Loc)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DnT, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BackToBT)
                        .addGap(63, 63, 63)
                        .addComponent(Conf)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Mov))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ForMAT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Langu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Loc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(sEAT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(DnT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Conf)
                    .addComponent(BackToBT))
                .addGap(55, 55, 55))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfActionPerformed
        // TODO add your handling code here:
        String user;
        //
        String host = "jdbc:derby://localhost:1527/Users";
       //strP=md5(strP);
String uName = "username";
String uPass= "password";
    int flag=0;
  
     try {
            Connection con;
      con = DriverManager.getConnection( host,uName,uPass);
      Statement stmt = con.createStatement();
      String SQL = "SELECT * FROM Data WHERE USERNAME='"+strU+"'";
      ResultSet rs=stmt.executeQuery(SQL);
      rs.next();
      user=rs.getString("CONTACT");
      SendEmail(user);
      String Cmd = "UPDATE SHOWS SET SEAT='"+seatmatrix+"' WHERE MOVIE='"+Mname+"' AND DATE='"+FinalDate+"' AND TIME='"+FinalTime+"'";
      stmt.executeUpdate(Cmd);
        } catch (SQLException ex) {
            Logger.getLogger(DBTest.class.getName()).log(Level.SEVERE, null, ex);
        }
                        
    
        //
        //SendEmail(user);
    }//GEN-LAST:event_ConfActionPerformed

    private void BackToBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToBTActionPerformed
        // TODO add your handling code here:
        BookedSeats="";
        for(int i=0;i<10;i++)
            count[i]=0;
        counti=0;
        dispose();
    }//GEN-LAST:event_BackToBTActionPerformed

    private void BackToBTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BackToBTKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            java.awt.event.ActionEvent e=null;
            BackToBTActionPerformed(e);
        }
    }//GEN-LAST:event_BackToBTKeyPressed

    private void ConfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ConfKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            java.awt.event.ActionEvent e=null;
            ConfActionPerformed(e);
        }
    }//GEN-LAST:event_ConfKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Confirmation c=new Confirmation();
                c.setVisible(true);
                c.setSize(new Dimension(517,454));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToBT;
    private javax.swing.JButton Conf;
    private javax.swing.JLabel DnT;
    private javax.swing.JLabel ForMAT;
    private javax.swing.JLabel Langu;
    private javax.swing.JLabel Loc;
    private javax.swing.JLabel Mov;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel sEAT;
    // End of variables declaration//GEN-END:variables
}
