/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mp1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import static mp1.Movies.Mname;
import static mp1.BookTicket.FinalDate;
import static mp1.BookTicket.FinalTime;

/**
 *
 * @author parth
 */
public class Seats extends javax.swing.JFrame {
 ResultSet rs;
 public char seatarray[];
        String seatmatrix;
    /**
     * Creates new form Seats
     */
    public Seats() {
       
         String host = "jdbc:derby://localhost:1527/Users";
        String uName = "username";
        String uPass= "password";
        try {
            Connection con;
      con = DriverManager.getConnection( host,uName,uPass);
      Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
      //String SQL = "SELECT * FROM Data";
      
      //Statement stmt = con.createStatement();
      System.out.println("Date: "+FinalDate+" and Time: "+FinalTime);
      
        String SQL = "SELECT* FROM SHOWS WHERE DATE='"+FinalDate+"' AND TIME='"+FinalTime+"'";
       
            try {
                 rs=stmt.executeQuery(SQL);
                 rs.next();
                 seatmatrix=rs.getString("SEAT");
                 System.out.println(seatmatrix);
                 seatarray=seatmatrix.toCharArray();
                 
                
                
                
                 
                 
                 
               
                
                 
                
                
                  
                    
            } 
            catch (SQLException ex) {
                Logger.getLogger(SignUP.class.getName()).log(Level.SEVERE, null, ex);
                
            }
      
                
        }
        catch(SQLException e){
                
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Seat1 = new javax.swing.JCheckBox();
        Seat2 = new javax.swing.JCheckBox();
        Seat4 = new javax.swing.JCheckBox();
        Seat5 = new javax.swing.JCheckBox();
        Seat3 = new javax.swing.JCheckBox();
        Seat6 = new javax.swing.JCheckBox();
        Seat7 = new javax.swing.JCheckBox();
        Seat8 = new javax.swing.JCheckBox();
        Seat9 = new javax.swing.JCheckBox();
        Seat10 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        BookS = new javax.swing.JButton();
        BackToBT = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("---------------------All eyes facing this way---------------------");

        Seat1.setBackground(new java.awt.Color(153, 153, 153));
        Seat1.setText("1");
        Seat1.setEnabled(seatarray[0]=='T'?true:false);
        Seat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat1ActionPerformed(evt);
            }
        });

        Seat2.setBackground(new java.awt.Color(153, 153, 153));
        Seat2.setText("2");
        Seat2.setEnabled(seatarray[1]=='T'?true:false);
        Seat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat2ActionPerformed(evt);
            }
        });

        Seat4.setBackground(new java.awt.Color(153, 153, 153));
        Seat4.setText("4");
        Seat4.setEnabled(seatarray[3]=='T'?true:false);
        Seat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat4ActionPerformed(evt);
            }
        });

        Seat5.setBackground(new java.awt.Color(153, 153, 153));
        Seat5.setText("5");
        Seat5.setEnabled(seatarray[4]=='T'?true:false);
        Seat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat5ActionPerformed(evt);
            }
        });

        Seat3.setBackground(new java.awt.Color(153, 153, 153));
        Seat3.setText("3");
        Seat3.setEnabled(seatarray[2]=='T'?true:false);
        Seat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat3ActionPerformed(evt);
            }
        });

        Seat6.setBackground(new java.awt.Color(153, 153, 153));
        Seat6.setText("6");
        Seat6.setEnabled(seatarray[5]=='T'?true:false);
        Seat6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat6ActionPerformed(evt);
            }
        });

        Seat7.setBackground(new java.awt.Color(153, 153, 153));
        Seat7.setText("7");
        Seat7.setEnabled(seatarray[6]=='T'?true:false);
        Seat7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat7ActionPerformed(evt);
            }
        });

        Seat8.setBackground(new java.awt.Color(153, 153, 153));
        Seat8.setText("8");
        Seat8.setEnabled(seatarray[7]=='T'?true:false);
        Seat8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat8ActionPerformed(evt);
            }
        });

        Seat9.setBackground(new java.awt.Color(153, 153, 153));
        Seat9.setText("9");
        Seat9.setEnabled(seatarray[8]=='T'?true:false);
        Seat9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat9ActionPerformed(evt);
            }
        });

        Seat10.setBackground(new java.awt.Color(153, 153, 153));
        Seat10.setText("10");
        Seat10.setEnabled(seatarray[9]=='T'?true:false);
        Seat10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat10ActionPerformed(evt);
            }
        });

        jLabel2.setText("Select your Seats");

        BookS.setBackground(new java.awt.Color(51, 255, 0));
        BookS.setText("Book");
        BookS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookSActionPerformed(evt);
            }
        });

        BackToBT.setBackground(new java.awt.Color(255, 0, 0));
        BackToBT.setText("Back");
        BackToBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Seat6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Seat7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Seat8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Seat9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Seat10))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Seat1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Seat2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Seat3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Seat4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Seat5)))
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BackToBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BookS)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookS)
                    .addComponent(BackToBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seat1)
                    .addComponent(Seat2)
                    .addComponent(Seat3)
                    .addComponent(Seat4)
                    .addComponent(Seat5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seat6)
                    .addComponent(Seat7)
                    .addComponent(Seat8)
                    .addComponent(Seat9)
                    .addComponent(Seat10))
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Seat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat1ActionPerformed
        // TODO add your handling code here:
        int i=Integer.parseInt(Seat1.getText())-1;
        if(seatarray[i]=='F')
            seatarray[i]='T';
        else
            seatarray[i]='F';
    }//GEN-LAST:event_Seat1ActionPerformed

    private void Seat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat2ActionPerformed
        // TODO add your handling code here:
         int i=Integer.parseInt(Seat2.getText())-1;
        if(seatarray[i]=='F')
            seatarray[i]='T';
        else
            seatarray[i]='F';
    }//GEN-LAST:event_Seat2ActionPerformed

    private void Seat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat4ActionPerformed
        // TODO add your handling code here:
         int i=Integer.parseInt(Seat4.getText())-1;
        if(seatarray[i]=='F')
            seatarray[i]='T';
        else
            seatarray[i]='F';
    }//GEN-LAST:event_Seat4ActionPerformed

    private void Seat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat5ActionPerformed
        // TODO add your handling code here:
         int i=Integer.parseInt(Seat5.getText())-1;
        if(seatarray[i]=='F')
            seatarray[i]='T';
        else
            seatarray[i]='F';
    }//GEN-LAST:event_Seat5ActionPerformed

    private void Seat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat3ActionPerformed
        // TODO add your handling code here:
         int i=Integer.parseInt(Seat3.getText())-1;
        if(seatarray[i]=='F')
            seatarray[i]='T';
        else
            seatarray[i]='F';
    }//GEN-LAST:event_Seat3ActionPerformed

    private void Seat6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat6ActionPerformed
        // TODO add your handling code here:
         int i=Integer.parseInt(Seat6.getText())-1;
        if(seatarray[i]=='F')
            seatarray[i]='T';
        else
            seatarray[i]='F';
    }//GEN-LAST:event_Seat6ActionPerformed

    private void Seat7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat7ActionPerformed
        // TODO add your handling code here:
         int i=Integer.parseInt(Seat7.getText())-1;
        if(seatarray[i]=='F')
            seatarray[i]='T';
        else
            seatarray[i]='F';
    }//GEN-LAST:event_Seat7ActionPerformed

    private void Seat8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat8ActionPerformed
        // TODO add your handling code here:
         int i=Integer.parseInt(Seat8.getText())-1;
        if(seatarray[i]=='F')
            seatarray[i]='T';
        else
            seatarray[i]='F';
    }//GEN-LAST:event_Seat8ActionPerformed

    private void Seat9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat9ActionPerformed
        // TODO add your handling code here:
         int i=Integer.parseInt(Seat9.getText())-1;
        if(seatarray[i]=='F')
            seatarray[i]='T';
        else
            seatarray[i]='F';
    }//GEN-LAST:event_Seat9ActionPerformed

    private void Seat10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat10ActionPerformed
        // TODO add your handling code here:
         int i=Integer.parseInt(Seat10.getText())-1;
        if(seatarray[i]=='F')
            seatarray[i]='T';
        else
            seatarray[i]='F';
    }//GEN-LAST:event_Seat10ActionPerformed

    private void BookSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookSActionPerformed
        // TODO add your handling code here:
        
        new Confirmation().setVisible(true);
    }//GEN-LAST:event_BookSActionPerformed

    private void BackToBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToBTActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BackToBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToBT;
    private javax.swing.JButton BookS;
    private javax.swing.JCheckBox Seat1;
    private javax.swing.JCheckBox Seat10;
    private javax.swing.JCheckBox Seat2;
    private javax.swing.JCheckBox Seat3;
    private javax.swing.JCheckBox Seat4;
    private javax.swing.JCheckBox Seat5;
    private javax.swing.JCheckBox Seat6;
    private javax.swing.JCheckBox Seat7;
    private javax.swing.JCheckBox Seat8;
    private javax.swing.JCheckBox Seat9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
